config/routes.rb
Rails.application.routes.draw do

  resources :gens, only: [:index,:new,:create,:edit,:update,:destroy] do   
    collection do  
      post :confirm
    end
  end
  
  root 'gens#index'
  
end

app/models/gen.rb
class Gen < ActiveRecord::Base
  validates :content, presence: true,
                      length: { minimum: 1, maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gens_controller.rb
class GensController < ApplicationController
  before_action :set_gen, only: [:edit, :destroy]
  
  def index
    @gens = Gen.all
  end
  
  def new
   if params[:back]
      @gen = Gen.new(gens_params)
   else
    @gen = Gen.new
   end
  end
  
  def confirm
   @gen = Gen.new(gens_params)
   render :new if @gen.invalid?
  end  
  
  def create
   @gen = Gen.new(gens_params)
   if @gen.save
      redirect_to gens_path, notice:"ツイッターを作成しました！"
   else
     render 'new'
   end     
  end
  
  def edit
    @gen = Gen.find(params[:id])
  end
  
  def update
    @gen = Gen.find(params[:id]) 
    @gen.update(gens_params)
     redirect_to gens_path, notice:"ツイッターを更新しました！"
  end
  
   
  def destroy
    @gen.destroy
    redirect_to gens_path, notice:"ツイッターを削除しました！"
  end
  
  private
    def gens_params
      params.require(:gen).permit(:content)
    end
    
    def set_gen
     @gen = Gen.find(params[:id])    
    end
 end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gens_helper.rb
module GensHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/gens/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1"><h3>以下の内容で、送信する。</h3>
<%= form_for(@gen) do |f| %>
  <%= f.hidden_field :content %>
  <p>本文:<%= @gen.content %></p>
  <%= f.submit "登録",class: 'btn btn-primary btn-block'  %>
<% end %>

<%= form_for(@gen, url: new_gen_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back',class: 'btn btn-default btn-block' %>
<% end %>
  </div>
</div>

app/views/gens/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<%= form_for(@gen) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>
  </div>
</div>

<%= link_to "ツイッター一覧画面にもどる", gens_path %>

app/views/gens/index.html.erb
<section class="main-header">
  <img src="images-master/achieve.png">
</section>
<section class="about">

<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<p><%= notice %></p>
<h1>ツイッター一覧</h1>
  <%= link_to "ツイッターを作成する", new_gen_path, class: 'btn btn-default' %>
<% @gens.each do |gen| %>
<div class="row">
  <p><%= gen.content %></p>
  <%= link_to "編集", edit_gen_path(gen.id), class: 'btn btn-default btn-sm btn-success' %>
  <%= link_to "削除", gen_path(gen.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
</div>
<% end %>
</div>
</div>

app/views/gens/new.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@gen,url: confirm_gens_path) do |f| %>
  <% if @gen.errors.any? %>
    <div id="error_explanation">
      <h2><%= @gen.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @gen.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
  <%= f.label :本文 %>
  <%= f.text_field :content,class: 'form-control' %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

  </div>
</div>
<%= link_to "ツイッター一覧画面にもどる", gens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Try</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

 <header>
   <ul>
      <li><%= link_to "トップページ", root_path %></li>
      <li><%= link_to "新規作成", new_gen_path %></li>
      <li><%= link_to "一覧表示",gens_path %></li>
   </ul> 
 </header>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>